### ISSUE TITLE
A bug in the tidykosmic R-packages

### ISSUE THREAD

**Issue by brachone** [divinenephron/tidykosmic#1]
Hello. When I run the tidykosmic package, an error shows: "No `kosmic` method is defined for the class `tbl_df'."

**Comment by divinenephron** [comment]
Thanks for giving it a try. Right now `kosmic` only works on vectors, so make sure you add a `$` and the column name after the data frame. It is `haemoglobin$result` in the example below.

```r
library(tidykosmic)
k <- kosmic(haemoglobin$result, decimals = 1)
```

I'll add data frame support some time soon.
